import base64
import difflib
import json
import logging
import os
import re
import subprocess
import sys
import urllib.parse
from collections import defaultdict
from functools import lru_cache
from typing import Iterable, Optional

import Levenshtein
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer


logger = logging.getLogger(__name__)

AI_GENERATED_DISCLAIMER = (
    "> **AI-generated content:** this report was generated by AI and may "
    "contain errors. Please verify important information.\n\n"
)


def remove_ai_generated_disclaimer(report: str) -> str:
    """Remove the disclaimer about AI-generated content from the beginning 
    of a report.
    """
    return report.removeprefix(AI_GENERATED_DISCLAIMER)


def write_generated_report(markdown_path: str, report: str) -> None:
    """Write a report with the AI-generated content disclaimer at the top.
    """
    if not report.startswith(AI_GENERATED_DISCLAIMER):
        report = AI_GENERATED_DISCLAIMER + report.lstrip("\n")

    with open(markdown_path, "w", encoding="utf-8") as report_file:
        report_file.write(report)


def parse_llm_json(response: str, 
                   max_chars: int = 100_000, 
                   max_depth: int = 20):
    """Extract and safely parse a size- and depth-limited JSON value."""
    if len(response) > max_chars:
        raise ValueError("LLM JSON response exceeds the size limit")

    start = next((i for i, char in enumerate(response) if char in "[{"), None)
    if start is None:
        raise ValueError("LLM response does not contain JSON")

    stack = []
    in_string = False
    escaped = False
    pairs = {"}": "{", "]": "["}
    for i in range(start, len(response)):
        char = response[i]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char in "[{":
            stack.append(char)
            if len(stack) > max_depth:
                raise ValueError("LLM JSON response exceeds the nesting limit")
        elif char in "]}":
            if not stack or stack.pop() != pairs[char]:
                raise ValueError("LLM response contains malformed JSON")
            if not stack:
                return json.loads(response[start:i + 1])

    raise ValueError("LLM response contains incomplete JSON")


def convert_markdown_to_html(
    markdown_path: str,
    html_path: str,
    *,
    css_path: str = "style/style.css",
    page_title: Optional[str] = None,
    embed_resources: bool = False,
    self_contained: bool = False,
    ) -> None:
    """Convert a Markdown file to HTML with Pandoc.
    """
    command = [
        "pandoc",
        "--css=" + os.path.abspath(css_path),
        "-s",
        "-o",
        html_path,
        markdown_path,
        "--mathml",
    ]
    if embed_resources:
        command.append("--embed-resources")
    if self_contained:
        command.append("--self-contained")
    if page_title is not None:
        command.extend(["--variable", f"pagetitle={page_title}"])

    subprocess.run(command, check=True)


def normalize_arxiv_url(url: str) -> str:
    """Normalize arXiv article URLs to their canonical PDF URL.
    """
    try:
        url = url.strip()
        parsed = urllib.parse.urlsplit(url)
        netloc = parsed.netloc.replace("www.", "")
        if netloc != "arxiv.org":
            return url

        match = re.match(
            r"^/(?:abs|pdf|html)/([0-9]+\.[0-9]+(?:\.[0-9]+)?)(v\d+)?(?:\.pdf)?/?$",
            parsed.path,
        )
        if not match:
            return urllib.parse.urlunsplit((parsed.scheme or "https", parsed.netloc, parsed.path, "", ""))

        paper_id, version = match.groups()
        return f"https://arxiv.org/pdf/{paper_id}{version or ''}"
    except Exception as e:
        logger.warning(e)
        return url

def remove_citations(text):
    # Remove citations in the form of [3], [8], [4] and [3] or similar
    text = re.sub(r"\[\d+(?:,\d+)*\]", "", text)  # Handles citations like [3],[8],[4]
    # Remove commas if they are followed directly by a space or a period after citation removal
    text = re.sub(r"\s*,\s*(?=\s*\.)", "", text)  # Remove the comma before a period
    text = re.sub(r" \[\d+", "", text)  # Remove citations with a space before them
    text = text.replace(" |", "").replace("]", "")  # Removes the pipe and extra closing brackets if present
    return text


def modify_latex_equations(text: str) -> str:
    """Given an input text, modify the LaTeX equations to make them 
    Markdown-friendly.
    
    Parameters
    ----------
    - text [`str`]: input text
    
    Output
    ------
    - `str`: text with modified equations
    """
    # 1) Convert block formulas \[...\] to $$ ... $$
    text = re.sub(r'\\\[(.*?)\\\]', 
                  lambda m: f'$$ {m.group(1).strip()} $$', 
                  text, 
                  flags=re.DOTALL)
    # 2) Convert inline formulas \(...\) to $...$ (no inner spaces next to $)
    text = re.sub(r'\\\((.*?)\\\)', 
                  lambda m: f'${m.group(1).strip()}$', 
                  text, 
                  flags=re.DOTALL)
    return text


@lru_cache(maxsize=None)
def _get_tokenizer(model_id: str):
    """Load each model tokenizer once and reuse it across token counts."""
    return AutoTokenizer.from_pretrained(model_id)


def get_number_tokens(text: str, model_id: str) -> int:
    """Get the number of tokens of a text for a given model.
    """
    try:
        tokenizer = _get_tokenizer(model_id)
        num_tokens = len(tokenizer(text)['input_ids'])
    except Exception as e:
        logger.warning(
            f"The tokenizer of the model {model_id} was not found in HF: '{e}'."
            "Using a proxy computation of the number of tokens."
        )        
        return len(text) // 6
    return num_tokens


def get_number_words(text: str) -> int:
    """Get the number of words of a given text.
    """
    count = len(re.findall(r'\w+', text))
    return count
    

def extract_markdown_sections(text, exclude_references=False):
    heading_pattern = r'^(#{1,6})\s+(.*)'

    sections = []
    current_section = None
    current_text = []

    for line in text.splitlines():
        match = re.match(heading_pattern, line)
        if match:
            if current_section is not None:
                sections.append((current_section, '\n'.join(current_text).strip() if current_text else ''))

            level = len(match.group(1))  # Number of # indicates the heading level
            section_title = match.group(2).strip()

            current_section = f"{'#' * level} {section_title}"
            current_text = []
        else:
            current_text.append(line.strip())

    if current_section is not None:
        sections.append((current_section, '\n'.join(current_text).strip() if current_text else ''))
    if exclude_references:
        sections = sections[:-1]
    return sections

def encode_image(image_path):
    if os.path.exists(image_path):
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode("utf-8")
    else:
        logger.info(f"Image path {image_path} does not exist")


def find_last_report_version(folder_path: str, stem: Optional[str]=None) -> int:
    """Check the files in the provided folder for labeled filenames containing
    the string '_v*'. Return the maximum number (corresponding to the latest
    version, or -1 in case of no match).
    
    Parameters
    ----------
    - folder_path [`str`]: path of the folder
    
    Output
    ------
    - `int`: the maximum version id
    """
    files = os.listdir(folder_path)
    
    pattern = r'_v(\d+)'
    version_numbers = []
    
    for filename in files:
        if (stem != None) and (stem not in filename):
            continue
        match = re.search(pattern, filename)
        if match:
            version_numbers.append(int(match.group(1)))
    
    return max(version_numbers, default=-1)


def filter_arxiv_url(urls: Iterable[str]) -> list[str]:
    """Given a list of URLs (not necessarily pointing to arxiv), if there are
    multiple versions of the same paper, keep only the most recent one. I.e., 
    if there is an URL without the version identifier consider that one as the
    most recent, otherwise keep the URL with the highest version identifier
    number.
    
    Parameters
    ----------
    - urls [`Iterable[str]`]: list of URLs to process

    Output
    ------
    - [`list`]: list of filtered urls
    """

    # Regex pattern to match URLs of arxiv paper and extract their
    # base identifier and version number
    arxiv_pattern = r"https://arxiv.org/(?:abs|pdf|html)/([0-9]+\.[0-9]+(?:\.[0-9]+)?)(v(\d+))?"
    
    urls = [normalize_arxiv_url(url) for url in urls]

    # defaultdict returns an empty list whenever accessing a non-existing key
    paper_groups = defaultdict(list)
    non_arxiv_urls = []
    
    for url in urls:
        match = re.fullmatch(arxiv_pattern, url)
        if match:
            base_paper_id = match.group(1)
            version_str = match.group(3)
            version = int(version_str) if version_str else None
            paper_groups[base_paper_id].append((url, version))
        else:
            non_arxiv_urls.append(url)
    
    result = []
    for base_paper_id, group in paper_groups.items():
        no_version_url = next(
            (url for url, version in group if version is None), 
            None
            )
        
        # If there is a version of the URL without the version identifier keep
        # that one, otherwise select the one with the maximum version number
        if no_version_url:
            result.append(no_version_url)
        else:
            latest_version_url = max(group, key=lambda x: x[1])[0]
            result.append(latest_version_url)
    
    result.extend(non_arxiv_urls)    

    for url in urls:
        if url not in result:
            logger.info((
                f"Removing URL {url} because it is not the latest version in "
                f"{str([t[0] for t in paper_groups[re.fullmatch(arxiv_pattern, url).group(1)]])}"
                ))
    return result

def handle_exception(exc_type, exc_value, exc_traceback):
    if issubclass(exc_type, KeyboardInterrupt):
        from utils.prompting import (total_input_tokens, total_output_tokens)
        logger.info("Total tokens before interrupt")
        logger.info(f"Total input tokens before interrupt: {total_input_tokens}")
        logger.info(f"Total output tokens before interrupt: {total_output_tokens}")
        print(f"[CRITICAL ERROR] {exc_type}\n{exc_value}\n{exc_traceback}")
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return

    logger.critical("[ERROR] Uncaught exception", 
                    exc_info=(exc_type, exc_value, exc_traceback))
    
    from utils.prompting import (total_input_tokens, total_output_tokens)
    logger.info("Total tokens before interrupt")
    logger.info(f"Total input tokens before interrupt: {total_input_tokens}")
    logger.info(f"Total output tokens before interrupt: {total_output_tokens}")
    print(f"[CRITICAL ERROR] {exc_type}\n{exc_value}\n{exc_traceback}")

def extract_level_headings(text: str, level: int = 2):
    heading_pattern = r"^(#{%d})\s(.+?)\n" % (level)
    headings = re.findall(heading_pattern, text, flags=re.MULTILINE)
    return [f"{level * '#'} {heading.strip()}" for _, heading in headings]

def convert_citations_to_superscript(text: str) -> str:
    """Detect the citations in the given text, with the format [integer, text].
    Convert them to small superscript, and remove the comma between multiple 
    consecutive citations.
    
    Parameters
    ----------
    - text [`str`]: input text
    
    Output
    ------
    - `str`: converted text
    """
    # This pattern matches the citations of the form [integer, text]
    citation_pattern = r'\[(\d+),\s*([^\]]+)\]'
    
    # This function will wrap the citation in superscript tags
    def superscript_match(match):
        citation_number = match.group(1)
        citation_text = match.group(2)
        return f'<sup><small>[{citation_number}, {citation_text}]</small></sup>'
    
    text_with_superscripts = re.sub(citation_pattern, superscript_match, text)
    
    # Remove the commas between multiple consecutive citations
    result_text = re.sub(r'</sup>,\s?<sup>', '</sup> <sup>', text_with_superscripts)
    
    return result_text


def remove_urls(text):
    # Match [[integer, text](url)]
    pattern = r'\[\[(\d+),([^\]]+)\]\([^\)]+\)\]'
    
    # Replace with [integer, text]
    def replacer(match):
        return f"[{match.group(1)}, {match.group(2).strip()}]"
    
    return re.sub(pattern, replacer, text)


def format_citations_to_superscript(text):
    # Match [[integer, text with spaces](url)]
    text = text.replace("<small><sup>", "").replace("</small></sup>","").replace("<sup><small>", "").replace("</sup></small>","")
    pattern = r'\[\[(\d+),([^\]]+)\]\([^\)]+\)\]'
    
    def replacer(match):
        citation = match.group(0)  # The full match, e.g., [[123, text](url)]
        return f"<small><sup>{citation}</sup></small>"
    
    text = re.sub(pattern, replacer, text)
    text = re.sub(r'</sup>,\s?<sup>', '</sup> <sup>', text)
    text = re.sub(r'</small>,\s?<small>', '</small> <small>', text)
    return text

def fix_citations(text: str, 
                  df: pd.DataFrame):
    # Match any citation like [1], [1, 2], [1, 2, 3], and so on
    pattern = re.compile(r'\[(\d+(?:\s*,\s*\d+)*)\]')

    def replacer(match):
        # Get the string inside the brackets, without the latters
        citation_ids = match.group(1)
        ids = [int(cid.strip()) for cid in citation_ids.split(',')]
        
        replaced = ''
        for cid in ids:
            try:
                citation_text = f", {df.at[cid - 1, 'identifier']}"
            except KeyError:
                citation_text = ''
            replaced += f'[{cid}{citation_text}]'
        
        return replaced

    return pattern.sub(replacer, text)

def find_section_of_text_unit(text_unit: str, 
                              report: str) -> str:
    """Given a text unit, it returns the (first) section where it appears.
    
    Parameters
    ----------
    - text_unit [`str`]: text snippet
    - report [`str`]: report

    Output
    ------
    - `str`: the updated version of the text unit or `None` if it was not found
    """
    sections = extract_markdown_sections(report, False)

    for sec in sections:
        if text_unit in sec[1]:
            return sec[1]
        
    if contains_markdown_table(text_unit):
        return find_section_of_text_unit(text_unit.strip().split("\n")[0], report)
    return None


def generate_subtables(table: str):
    """Given a string that represents a table in markdown format, generate the
    subtables, each containing the header and one of the row of the table.
    
    Parameters
    ----------
    - table [`str`]: the table in markdown format
    
    Output
    - `list[str]`: list of subtables in markdown format
    """
    table_lines = table.strip().split("\n")

    # Usually the first contains headings, and the second the divider: use
    # this as default setting
    divider_index = 2
    for i, line in enumerate(table_lines):
        if line.upper().isupper() == False:
            divider_index = i + 1

    table_header = "\n".join(table_lines[:divider_index])

    subtables = []
    for line in table_lines[divider_index:]:
        subtables.append("\n".join([table_header, line]))
    return subtables


def contains_markdown_table(text_unit: str) -> bool:
    lines = text_unit.strip().splitlines()
    for i in range(len(lines) - 1):
        header = lines[i].strip()
        separator = lines[i + 1].strip()
        
        # Check if both header and separator use pipe characters
        if '|' in header and '|' in separator:
            # Check for the separator line pattern: at least three dashes between pipes
            if re.fullmatch(r'\s*\|?( *:?-+:? *\|)+ *:?-+:? *\|?\s*', separator):
                return True
    return False

class TextSimilarityEvaluator():
    def __init__(self):
        pass

    def sequence_matcher(self, text1: str, text2: str):
        similarity = difflib.SequenceMatcher(None, text1, text2).ratio()
        return similarity
    
    def jaccard_similarity(self, text1: str, text2: str):
        words1 = set(text1.lower().split())
        words2 = set(text2.lower().split())
        intersection = words1.intersection(words2)
        union = words1.union(words2)
        similarity = len(intersection) / len(union)
        return similarity
    
    def tfidf_similarity(self, text1: str, text2: str):
        vectorizer = TfidfVectorizer()
        tfidf = vectorizer.fit_transform([text1, text2])
        similarity = cosine_similarity(tfidf[0:1], tfidf[1:2])[0][0]
        return similarity
    
    def embedding_similarity(self, 
                             text1: str, 
                             text2: str, 
                             model_id: str = "allenai-specter"):
        # Load the embedding model
        model = SentenceTransformer(model_id)
        # Compute the embeddings
        emb1 = model.encode(text1, convert_to_tensor=True)
        emb2 = model.encode(text2, convert_to_tensor=True)
        similarity = SentenceTransformer.util.pytorch_cos_sim(emb1, emb2).item()
        return similarity
    
    def levenshtein_distance(self,
                             text1: str,
                             text2: str,
                             convert_to_sim: bool = True):
        distance = Levenshtein.distance(text1, text2) / max(len(text1), len(text2))
        if convert_to_sim: 
            return 1 - distance
        else:
            return distance        


class MarkdownTableHandler:
    def __init__(self):
        pass

    def hide_tables(self, text):
        table_regex = re.compile(
            r'(?:\|.*\|\s*\n)+\|(?:\s*:?-+:?\s*\|)+\s*\n(?:\|.*\|\s*\n?)+',
            re.MULTILINE
        )
        return table_regex.sub('', text).strip()

    def extract_markdown_tables(self, text):
        table_regex = re.compile(
            r'(?:\|.*\|\s*\n)+\|(?:\s*:?-+:?\s*\|)+\s*\n(?:\|.*\|\s*\n?)+',
            re.MULTILINE
        )
        
        tables = table_regex.findall(text)
        return [table.strip() for table in tables]

def remove_surrounding_quotes(s):
    for quote in ('"', "'"):
        count = 0
        while s.startswith(quote * (count + 1)) and s.endswith(quote * (count + 1)):
            count += 1
        if count > 0:
            return s[count:-count]
    return s
